/*

 RENDER01_MAP_ENTITYS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\dixon\Documentos\gb\gbdk-linux64\gbdk\examples\gb\ejemplos\ejemplo02\src\game\Renderer\Render01\render01_tile.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define render01_map_entitysWidth 20
#define render01_map_entitysHeight 18
#define render01_map_entitysBank 0

extern unsigned char render01_map_entitys[];

/* End of RENDER01_MAP_ENTITYS.H */
