//AUTOGENERATED FILE FROM png2asset
// Conversion args: /corazon_16x16.png -sw 16 -sh 16 -spr8x8 -c /corazon.c

#ifndef METASPRITE_corazon_H
#define METASPRITE_corazon_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define corazon_TILE_ORIGIN 0
#define corazon_TILE_W 8
#define corazon_TILE_H 8
#define corazon_WIDTH 16
#define corazon_HEIGHT 16
#define corazon_TILE_COUNT 10
#define corazon_PALETTE_COUNT 1
#define corazon_COLORS_PER_PALETTE 4
#define corazon_TOTAL_COLORS 4
#define corazon_PIVOT_X 8
#define corazon_PIVOT_Y 8
#define corazon_PIVOT_W 16
#define corazon_PIVOT_H 16
extern const metasprite_t* const corazon_metasprites[4];

BANKREF_EXTERN(corazon)

extern const palette_color_t corazon_palettes[4];
extern const uint8_t corazon_tiles[160];

#endif
