//AUTOGENERATED FILE FROM png2asset
// Conversion args: /man_32x32.png -sw 32 -sh 32 -spr8x8 -c /man.c

#ifndef METASPRITE_man_H
#define METASPRITE_man_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define man_TILE_ORIGIN 0
#define man_TILE_W 8
#define man_TILE_H 8
#define man_WIDTH 32
#define man_HEIGHT 32
#define man_TILE_COUNT 23
#define man_PALETTE_COUNT 1
#define man_COLORS_PER_PALETTE 4
#define man_TOTAL_COLORS 4
#define man_PIVOT_X 16
#define man_PIVOT_Y 16
#define man_PIVOT_W 32
#define man_PIVOT_H 32
extern const metasprite_t* const man_metasprites[2];

BANKREF_EXTERN(man)

extern const palette_color_t man_palettes[4];
extern const uint8_t man_tiles[368];

#endif
